project_id = "lztmpbxmntcktijcdcda"

[functions.upload-object-image]
verify_jwt = true

[functions.generate-object-image]
verify_jwt = true

[functions.list-object-images]
verify_jwt = true

[functions.delete-object-image]
verify_jwt = true

[functions.set-primary-image]
verify_jwt = true
