create table if not exists public.recent_shows (
  id bigint generated by default as identity primary key,
  user_id integer not null references public.users(id) on delete cascade,
  tmdb_id integer not null,
  show_name text not null check (char_length(btrim(show_name)) between 1 and 500),
  poster_path text,
  last_used_at timestamp with time zone not null default now(),
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  unique (user_id, tmdb_id)
);

create index if not exists idx_recent_shows_user_last_used
on public.recent_shows(user_id, last_used_at desc);

alter table public.recent_shows enable row level security;

drop policy if exists "Users can view their own recent shows" on public.recent_shows;
create policy "Users can view their own recent shows"
on public.recent_shows for select
using (
  exists (
    select 1 from public.users
    where users.id = recent_shows.user_id
      and users.clerk_user_id = auth.uid()::text
  )
);

drop policy if exists "Users can insert their own recent shows" on public.recent_shows;
create policy "Users can insert their own recent shows"
on public.recent_shows for insert
with check (
  exists (
    select 1 from public.users
    where users.id = recent_shows.user_id
      and users.clerk_user_id = auth.uid()::text
  )
);

drop policy if exists "Users can update their own recent shows" on public.recent_shows;
create policy "Users can update their own recent shows"
on public.recent_shows for update
using (
  exists (
    select 1 from public.users
    where users.id = recent_shows.user_id
      and users.clerk_user_id = auth.uid()::text
  )
)
with check (
  exists (
    select 1 from public.users
    where users.id = recent_shows.user_id
      and users.clerk_user_id = auth.uid()::text
  )
);

drop policy if exists "Users can delete their own recent shows" on public.recent_shows;
create policy "Users can delete their own recent shows"
on public.recent_shows for delete
using (
  exists (
    select 1 from public.users
    where users.id = recent_shows.user_id
      and users.clerk_user_id = auth.uid()::text
  )
);
